# Generated by Django 4.0.5 on 2022-06-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profile_user'),
        ('api', '0007_song_spotify_uri'),
    ]

    operations = [
    ]
