# Generated by Django 4.0.5 on 2022-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_0007_alter_profile_user_0007_song_spotify_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.TextField(default='', max_length=255),
        ),
    ]
