# Generated by Django 4.0.5 on 2022-06-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_mixtape_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
