# Generated by Django 4.0.5 on 2022-06-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_mixtape_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
