# Generated by Django 4.0.5 on 2022-06-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_profile_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mixtape',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
