# Generated by Django 4.0.5 on 2022-07-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_profile_apple_username_profile_spotify_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='apple_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='spotify_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
