# Generated by Django 4.0.5 on 2022-07-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_image_profile_alter_profile_followed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="api.profile",
            ),
        ),
    ]
