# Generated by Django 4.0.5 on 2022-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_image_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='api.image'),
        ),
    ]
