# Generated by Django 4.0.5 on 2022-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, related_name='profiles', to='api.profile'),
        ),
    ]
